import type { PresetPack } from '../types/ingredients';

export const PRESET_PACKS: PresetPack[] = [
  {
    id: 'common-food-allergens',
    name: 'Common Food Allergens',
    description: 'Major food allergens recognized by labeling regulations. Keyword list only — not medical advice.',
    category: 'allergen',
    terms: [
      { label: 'Milk', aliases: ['lactose', 'casein', 'whey', 'milk protein', 'milk powder', 'condensed milk', 'evaporated milk', 'süt', 'laktoz', 'süt tozu', 'süt proteini', 'kazein', 'peynir altı suyu'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Egg', aliases: ['eggs', 'albumin', 'lysozyme', 'ovomucin', 'egg white', 'egg yolk', 'egg powder', 'egg lecithin', 'yumurta', 'yumurta akı', 'yumurta sarısı', 'yumurta tozu', 'yumurta lesitini'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Fish', aliases: ['cod', 'salmon', 'anchovy', 'sardine', 'tuna', 'haddock', 'trout', 'mackerel', 'herring', 'pollock', 'tilapia', 'catfish', 'halibut', 'balık', 'somon', 'ton', 'ton balığı', 'hamsi', 'sardalya', 'uskumru', 'alabalık', 'morina'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Shellfish', aliases: ['shrimp', 'crab', 'lobster', 'prawn', 'crawfish', 'mussel', 'oyster', 'scallop', 'clam', 'kabuklu deniz', 'karides', 'istakoz', 'yengeç', 'midye', 'istiridye', 'deniz tarağı'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Tree Nuts', aliases: ['almond', 'cashew', 'walnut', 'pecan', 'pistachio', 'hazelnut', 'macadamia', 'brazil nut', 'pine nut', 'chestnut', 'butternut', 'ginkgo nut', 'kolanuts', 'fındık', 'badem', 'ceviz', 'antep fıstığı', 'kaju', 'fıstık', 'çam fıstığı', 'kestane', 'macadamia'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Peanuts', aliases: ['peanut', 'arachis hypogaea', 'peanut butter', 'peanut oil', 'peanut flour', 'ground nut', 'yer fıstığı', 'yer fıstığı yağı', 'fıstık ezmesi'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Wheat', aliases: ['wheat flour', 'wheat starch', 'wheat gluten', 'wheat protein', 'wheat bran', 'wheat germ', 'spelt', 'kamut', 'farro', 'durum', 'emmer', 'einkorn', 'buğday', 'buğday unu', 'buğday nişastası', 'tam buğday', 'bulgur', 'irmik'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Gluten', aliases: ['wheat gluten', 'barley', 'rye', 'oat gluten', 'triticale', 'barley malt', 'malt extract', 'malt vinegar', 'brewer yeast', 'gluten', 'glüten', 'arpa', 'çavdar', 'malt', 'malt özü', 'bira mayası'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Soy', aliases: ['soybean', 'soya', 'soy lecithin', 'soy protein', 'soy flour', 'soy oil', 'soy milk', 'soy sauce', 'tofu', 'edamame', 'miso', 'tempeh', 'soja', 'soya lesitini', 'soya proteini', 'soya unu', 'soya sütü', 'tofu'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Sesame', aliases: ['sesame seeds', 'sesame oil', 'tahini', 'sesame paste', 'sesame flour', 'sesame salt', 'gomasio', 'susam', 'susam yağı', 'tahin', 'tahin helva'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Celery', aliases: ['celery seed', 'celery salt', 'celery extract', 'celery root', 'celeriac', 'kereviz', 'kereviz tohumu', 'kereviz tuzu', 'kereviz özü'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Mustard', aliases: ['mustard seed', 'mustard oil', 'mustard flour', 'mustard powder', 'mustard greens', 'yellow mustard', 'brown mustard', 'hardal', 'hardal tohumu', 'hardal yağı', 'hardal unu'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Lupin', aliases: ['lupin bean', 'lupin flour', 'lupin protein', 'lupin seed', 'lupini beans', 'lupin tohumu', 'acı bakla'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Molluscs', aliases: ['snail', 'squid', 'cuttlefish', 'octopus', 'abalone', 'sea urchin', 'escargot', 'salyangoz', 'ahtapot', 'kalamar', 'mürekkep balığı'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Sulphites', aliases: ['sulfites', 'sulphur dioxide', 'sodium sulfite', 'sodium bisulfite', 'potassium bisulfite', 'potassium metabisulfite', 'sodium metabisulfite', 'E220', 'E221', 'E222', 'E223', 'E224', 'E225', 'E226', 'E227', 'E228', 'sülfit', 'kükürt dioksit', 'sodyum sülfit', 'sodyum metabisülfit', 'potasyum metabisülfit'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Corn', aliases: ['maize', 'corn starch', 'corn syrup', 'corn flour', 'corn oil', 'cornmeal', 'popcorn', 'corn gluten', 'mısır', 'mısır nişastası', 'mısır şurubu', 'mısır unu', 'mısır yağı'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Coconut', aliases: ['coconut oil', 'coconut milk', 'coconut cream', 'coconut water', 'coconut flour', 'coconut butter', 'hindistan cevizi', 'hindistan cevizi yağı', 'hindistan cevizi sütü', 'krem hindistan cevizi'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Garlic', aliases: ['sarımsak', 'sarımsak tozu', 'sarımsak özü', 'garlic powder', 'garlic extract', 'garlic oil'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Kiwi', aliases: ['kivi'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Banana', aliases: ['muz'], category: 'allergen', severity: 'warning', enabled: true },
    ],
  },
  {
    id: 'vegan-animal-derived',
    name: 'Vegan / Animal-Derived',
    description: 'Ingredients derived from animals. Keyword list only — not a vegan certification.',
    category: 'vegan',
    terms: [
      { label: 'Gelatin', aliases: ['gelatine', 'gel', 'hydrolyzed gelatin', 'jelatin'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Collagen', aliases: ['hydrolyzed collagen', 'marine collagen', 'bovine collagen', 'fish collagen', 'kolajen', 'hidrolize kolajen', 'deniz kolajeni', 'sığır kolajeni', 'balık kolajeni'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Carmine', aliases: ['cochineal', 'carminic acid', 'CI 75470', 'E120', 'natural red 4', 'karmin', 'kokineal'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Lanolin', aliases: ['wool wax', 'wool grease', 'lanolin alcohol', 'lanolin yağı', 'yün mumu'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Beeswax', aliases: ['cera alba', 'cire d\'abeille', 'honey wax', 'balmumu', 'arı mumu'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Casein', aliases: ['sodium caseinate', 'calcium caseinate', 'potassium caseinate', 'casein hydrolysate', 'kazein', 'sodyum kazeinat', 'kalsiyum kazeinat'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Whey', aliases: ['whey protein', 'whey powder', 'whey isolate', 'whey concentrate', 'peynir altı suyu', 'whey proteini', 'peynir altı suyu proteini'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Shellac', aliases: ['confectioner\'s glaze', 'lac resin', 'E904', 'gomalak'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Tallow', aliases: ['rendered fat', 'sodium tallowate', 'beef tallow', 'mutton tallow', 'tallow amine', 'iç yağı', 'don yağı', 'sığır iç yağı', 'kuyruk yağı'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Honey', aliases: ['bal', 'arı balı'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Keratin', aliases: ['hydrolyzed keratin', 'keratin protein', 'keratin', 'keratin amino acids'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Silk', aliases: ['silk amino acid', 'hydrolyzed silk', 'sericin', 'silk protein', 'silk powder', 'ipek', 'ipek proteini', 'sirisin'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Elastin', aliases: ['hydrolyzed elastin', 'elastin protein', 'elastin', 'elastin amino acids'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Cholesterol', aliases: ['cholesterol', 'kolesterol'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Stearic Acid', aliases: ['stearate', 'magnesium stearate', 'calcium stearate', 'zinc stearate', 'stearik asit', 'magnezyum stearat', 'kalsiyum stearat'], category: 'vegan', severity: 'notice', enabled: true },
      { label: 'Rennet', aliases: ['rennin', 'chymosin', 'peynir mayası', 'rennet', 'renin'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Isinglass', aliases: ['fish glue', 'balık tutkalı'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Squalene', aliases: ['squalane', 'olive squalane', 'shark squalene', 'köpek balığı yağı', 'skualen', 'skualan'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Vitamin D3', aliases: ['cholecalciferol', 'lanolin vitamin D', 'D3'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Musk', aliases: ['misk'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Ambergris', aliases: ['amber', 'ambra'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Bone Char', aliases: ['animal charcoal', 'bone black', 'kemik kömürü', 'hayvansal kömür'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Ghee', aliases: ['clarified butter', 'sade yağ'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Guanine', aliases: ['CI 75170', 'pearl essence', 'guanin'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Cochineal', aliases: ['cochineal extract', 'carmine', 'E120', 'natural red', 'kokineal', 'karmin'], category: 'vegan', severity: 'warning', enabled: true },
    ],
  },
  {
    id: 'cosmetics-watchlist',
    name: 'Cosmetics Watchlist',
    description: 'Common cosmetic ingredients some users prefer to avoid. Keyword list only — not dermatology advice.',
    category: 'cosmetics',
    terms: [
      { label: 'Paraben', aliases: ['methylparaben', 'propylparaben', 'butylparaben', 'ethylparaben', 'isobutylparaben', 'isopropylparaben', 'benzylparaben', 'sodium methylparaben', 'potassium paraben', 'parabenler', 'paraben'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Fragrance', aliases: ['parfum', 'perfume', 'aroma', 'fragrance oil', 'fragrance blend', 'essence', 'essential oil blend', 'parfüm', 'koku', 'parfümlü', 'esans'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Alcohol Denat', aliases: ['alcohol denatured', 'SD alcohol', 'denatured alcohol', 'denatüre alkol', 'etanol denat', 'ethanol denat'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'SLS', aliases: ['sodium lauryl sulfate', 'sodium dodecyl sulfate', 'sodium dodecyl sulphate', 'sodyum lauril sülfat'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'SLES', aliases: ['sodium laureth sulfate', 'sodium lauryl ether sulfate', 'sodium laureth sulphate', 'sodyum lauret sülfat'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Phthalate', aliases: ['diethyl phthalate', 'DBP', 'DEHP', 'DEP', 'phthalates', 'dibutyl phthalate', 'benzyl butyl phthalate', 'ftalat', 'ftalatlar'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Formaldehyde', aliases: ['formalin', 'formaldehyde releaser', 'DMDM hydantoin', 'quaternium-15', 'imidazolidinyl urea', 'diazolidinyl urea', 'bronopol', 'formaldehit', 'formaldehit salıcı'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Triclosan', aliases: ['triclocarban', 'microban', 'triklosan', 'triklokarban'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'BHA', aliases: ['butylated hydroxyanisole', 'E320', 'BHA'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'BHT', aliases: ['butylated hydroxytoluene', 'E321', 'BHT'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Mineral Oil', aliases: ['paraffinum liquidum', 'petrolatum', 'mineral oil', 'paraffin', 'mineral yağ', 'parafin', 'vazelin'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'Dimethicone', aliases: ['cyclomethicone', 'cyclotetrasiloxane', 'cyclopentasiloxane', 'silicone', 'dimethiconol', 'dimetikon', 'silikon', 'siklopentasiloksan'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'Oxybenzone', aliases: ['benzophenone-3', 'BP-3', 'oxybenzone', 'oksibenzon', 'benzofenon-3'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Octinoxate', aliases: ['ethylhexyl methoxycinnamate', 'octyl methoxycinnamate', 'OMC', 'oktinoksat', 'etilheksil metoksisinnamat'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Coal Tar', aliases: ['coal tar dye', 'CI 77266', 'D&C Black', 'D&C Red', 'coal tar solution', 'kömür katranı', 'kömür katranı boyası'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Hydroquinone', aliases: ['hydroquinone', 'hidrokinon'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Toluene', aliases: ['toluene', 'toluen', 'methylbenzene'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Methylisothiazolinone', aliases: ['MI', 'MIT', 'methylchloroisothiazolinone', 'MCI', 'metilizotiyazolinon', 'metilkloroizotiyazolinon'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Propylene Glycol', aliases: ['propanediol', 'PG', 'propilen glikol', 'propanediol'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'DEA', aliases: ['diethanolamine', 'MEA', 'monoethanolamine', 'TEA', 'triethanolamine', 'cocamide DEA', 'cocamide MEA', 'lauryl diethanolamine', 'dietanolamin', 'trietanolamin', 'kokamid DEA'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Phenoxyethanol', aliases: ['phenoxyethanol', 'fenoksietanol'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'Synthetic Fluorphlogopite', aliases: ['synthetic fluorphlogopite', 'mica', 'sentetika mika', 'sentetik floroflogopit'], category: 'cosmetics', severity: 'info', enabled: true },
      { label: 'PEG', aliases: ['polyethylene glycol', 'PEG-8', 'PEG-40', 'PEG-100', 'PEG-12', 'PEG-20', 'PEG-60', 'PEG-80', 'polietilen glikol', 'PEG'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'Retinyl Palmitate', aliases: ['retinyl palmitate', 'retinol palmitate', 'vitamin A palmitate', 'retinol palmitat'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'Talc', aliases: ['talcum powder', 'talc', 'talk'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'Sodium Benzoate', aliases: ['E211', 'sodium benzoate', 'sodyum benzoat', 'sodium benzoic acid'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'Potassium Sorbate', aliases: ['E202', 'potassium sorbate', 'potasyum sorbat'], category: 'cosmetics', severity: 'info', enabled: true },
      { label: 'Triclocarban', aliases: ['triclocarban', 'TCC', 'triklokarban'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Homosalate', aliases: ['homosalate', 'homosalat'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'Octocrylene', aliases: ['octocrylene', 'oktokrilen'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'Nanoparticles', aliases: ['nano zinc oxide', 'nano titanium dioxide', 'nano partikül', 'nanopartikül', 'nano'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'Resorcinol', aliases: ['resorcinol', 'resorsinol'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Cocamidopropyl Betaine', aliases: ['cocamidopropyl betaine', 'CAPB', 'kokamidopropil betain'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'Aluminum', aliases: ['aluminum chloride', 'aluminum chlorohydrate', 'aluminum zirconium', 'aluminyum', 'alüminyum klorhidrat'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Microplastics', aliases: ['polyethylene', 'polypropylene', 'nylon-12', 'nylon-6', 'polietilen', 'polipropilen', 'mikroplastik', 'mikro boncuk'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Lactic Acid', aliases: ['lactic acid', 'laktik asit'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'Urea', aliases: ['urea', 'carbamide', 'imidazolidinyl urea', 'üre'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'Benzalkonium Chloride', aliases: ['benzalkonium chloride', 'benzalkonyum klorür'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'Sodium Chloride', aliases: ['sodium chloride', 'sodyum klorür', 'tuz', 'deniz tuzu'], category: 'cosmetics', severity: 'info', enabled: true },
      { label: 'Ethanolamine', aliases: ['ethanolamine', 'ethanolamin', 'aminoethanol'], category: 'cosmetics', severity: 'notice', enabled: true },
    ],
  },
  {
    id: 'sensitive-skin',
    name: 'Sensitive Skin Irritants',
    description: 'Common skin irritants that may cause reactions for sensitive skin types. Keyword list only — not dermatology advice.',
    category: 'sensitive_skin',
    terms: [
      { label: 'Fragrance', aliases: ['parfum', 'perfume', 'aroma', 'parfüm', 'koku', 'esans'], category: 'sensitive_skin', severity: 'warning', enabled: true },
      { label: 'Alcohol Denat', aliases: ['alcohol denatured', 'SD alcohol', 'denatured alcohol', 'denatüre alkol'], category: 'sensitive_skin', severity: 'warning', enabled: true },
      { label: 'SLS', aliases: ['sodium lauryl sulfate', 'sodium dodecyl sulfate', 'sodyum lauril sülfat'], category: 'sensitive_skin', severity: 'warning', enabled: true },
      { label: 'SLES', aliases: ['sodium laureth sulfate', 'sodyum lauret sülfat'], category: 'sensitive_skin', severity: 'warning', enabled: true },
      { label: 'Methylisothiazolinone', aliases: ['MI', 'MIT', 'methylchloroisothiazolinone', 'MCI', 'metilizotiyazolinon'], category: 'sensitive_skin', severity: 'warning', enabled: true },
      { label: 'Propylene Glycol', aliases: ['propanediol', 'PG', 'propilen glikol'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'Lanolin', aliases: ['wool wax', 'lanolin alcohol', 'lanolin yağı'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'DEA', aliases: ['diethanolamine', 'triethanolamine', 'cocamide DEA', 'cocamide MEA', 'trietanolamin', 'dietanolamin'], category: 'sensitive_skin', severity: 'warning', enabled: true },
      { label: 'Phenoxyethanol', aliases: ['phenoxyethanol', 'fenoksietanol'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'Retinol', aliases: ['retinol', 'retinoic acid', 'tretinoin', 'retinoid', 'retinaldehyde', 'retinol palmitate', 'retinoik asit'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'Glycolic Acid', aliases: ['glycolic acid', 'AHA', 'alpha hydroxy acid', 'glikolik asit', 'alfa hidroksi asit'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'Salicylic Acid', aliases: ['BHA', 'beta hydroxy acid', 'salisilik asit', 'beta hidroksi asit'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'Benzoyl Peroxide', aliases: ['benzoyl peroxide', 'benzoil peroksit'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'Essential Oil', aliases: ['essential oil blend', 'volatile oil', 'uçucu yağ', 'eterik yağ'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'Eucalyptus', aliases: ['eucalyptus oil', 'eucalyptol', 'okaliptüs', 'okaliptüs yağı'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'Peppermint', aliases: ['menthol', 'mentha piperita', 'nane yağı', 'mentol'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'Camphor', aliases: ['camphor', 'kapfor', 'kafur'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'Witch Hazel', aliases: ['hamamelis', 'witch hazel', 'cadı fındığı'], category: 'sensitive_skin', severity: 'info', enabled: true },
      { label: 'Citric Acid', aliases: ['citric acid', 'limon asidi', 'sitrik asit'], category: 'sensitive_skin', severity: 'info', enabled: true },
      { label: 'Sodium Hydroxide', aliases: ['lye', 'caustic soda', 'sodyum hidroksit', 'kostik soda'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'Vitamin C', aliases: ['ascorbic acid', 'L-ascorbic acid', 'C vitamin', 'askorbik asit'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'Niacinamide', aliases: ['niacinamide', 'nicotinamide', 'niacin', 'niyasinamid', 'nikotinamid'], category: 'sensitive_skin', severity: 'info', enabled: true },
      { label: 'Tea Tree Oil', aliases: ['tea tree', 'melaleuca oil', 'çay ağacı yağı'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'Cinnamon Oil', aliases: ['cinnamon bark oil', 'cinnamaldehyde', 'tarçın yağı', 'tarçın kabuğu yağı'], category: 'sensitive_skin', severity: 'warning', enabled: true },
      { label: 'Clove Oil', aliases: ['clove', 'eugenol', 'karanfil yağı', 'öjenol'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'Lavender Oil', aliases: ['lavender', 'lavandula', 'lavanta yağı'], category: 'sensitive_skin', severity: 'notice', enabled: true },
    ],
  },
  {
    id: 'cleaning-products',
    name: 'Cleaning Product Watchlist',
    description: 'Chemicals found in household cleaning products. Keyword list only — not safety advice.',
    category: 'cleaning',
    terms: [
      { label: 'Chlorine', aliases: ['sodium hypochlorite', 'chlorine bleach', 'chlorine dioxide', 'hypochlorous acid', 'klor', 'hipoklorit', 'sodyum hipoklorit', 'klor dioksit'], category: 'cleaning', severity: 'warning', enabled: true },
      { label: 'Ammonia', aliases: ['ammonium hydroxide', 'ammonia solution', 'ammonia water', 'amonyak', 'amonyum hidroksit'], category: 'cleaning', severity: 'warning', enabled: true },
      { label: 'Bleach', aliases: ['sodium hypochlorite', 'chlorine bleach', 'oxygen bleach', 'hydrogen peroxide bleach', 'çamaşır suyu', 'ağartıcı', 'oksijenli ağartıcı'], category: 'cleaning', severity: 'warning', enabled: true },
      { label: 'Fragrance', aliases: ['parfum', 'perfume', 'aroma', 'scent', 'parfüm', 'koku', 'esans'], category: 'cleaning', severity: 'notice', enabled: true },
      { label: 'Quats', aliases: ['quaternary ammonium compounds', 'benzalkonium chloride', 'ADBAC', 'cetrimonium bromide', 'cetrimonium chloride', 'didecyl dimethyl ammonium', 'kuarterner amonyum', 'benzalkonyum klorür', 'setrimonyum klorür'], category: 'cleaning', severity: 'warning', enabled: true },
      { label: 'Phosphates', aliases: ['sodium tripolyphosphate', 'STPP', 'trisodium phosphate', 'tetrasodium phosphate', 'fosfat', 'sodyum trifosfat', 'sodyum fosfat'], category: 'cleaning', severity: 'notice', enabled: true },
      { label: 'Optical Brighteners', aliases: ['fluorescent brightening agents', 'FBA', 'tinopal', 'CBS-X', 'optik beyazlatıcı', 'floresan beyazlatıcı'], category: 'cleaning', severity: 'notice', enabled: true },
      { label: 'Triclosan', aliases: ['triclocarban', 'microban', 'triklosan'], category: 'cleaning', severity: 'warning', enabled: true },
      { label: 'Nonylphenol', aliases: ['nonylphenol ethoxylate', 'NPE', 'nonilfenol', 'nonilfenol etoksilat'], category: 'cleaning', severity: 'warning', enabled: true },
      { label: 'MEA', aliases: ['monoethanolamine', 'MEA', 'etanolamin', 'monoetanolamin'], category: 'cleaning', severity: 'notice', enabled: true },
      { label: '2-Butoxyethanol', aliases: ['ethylene glycol monobutyl ether', 'EGBE', 'bütoksietanol', 'etilen glikol monobutil eter'], category: 'cleaning', severity: 'warning', enabled: true },
      { label: 'EDTA', aliases: ['ethylenediaminetetraacetic acid', 'tetrasodium EDTA', 'disodium EDTA', 'EDTA'], category: 'cleaning', severity: 'notice', enabled: true },
      { label: 'Hydrogen Peroxide', aliases: ['hydrogen peroxide', 'H2O2', 'hidrojen peroksit', 'oksijenli su'], category: 'cleaning', severity: 'notice', enabled: true },
      { label: 'Borax', aliases: ['sodium borate', 'sodium tetraborate', 'borax', 'boraks', 'sodyum borat', 'sodyum tetraborat'], category: 'cleaning', severity: 'notice', enabled: true },
      { label: 'Sodium Carbonate', aliases: ['sodium carbonate', 'washing soda', 'soda ash', 'sodyum karbonat', 'çamaşır sodası'], category: 'cleaning', severity: 'info', enabled: true },
      { label: 'Enzymes', aliases: ['protease', 'lipase', 'amylase', 'cellulase', 'mannanase', 'pektinaz', 'enzim', 'enzimler'], category: 'cleaning', severity: 'notice', enabled: true },
      { label: 'Phenol', aliases: ['phenol', 'carbolic acid', 'fenol', 'karbolik asit'], category: 'cleaning', severity: 'warning', enabled: true },
      { label: 'Chloramine', aliases: ['chloramine-T', 'chloramine', 'kloramin', 'kloramin-T'], category: 'cleaning', severity: 'warning', enabled: true },
      { label: 'Sulfamic Acid', aliases: ['sulfamic acid', 'sülfamik asit'], category: 'cleaning', severity: 'notice', enabled: true },
    ],
  },
  {
    id: 'food-additives',
    name: 'Food Additives to Watch',
    description: 'Common food additives some users prefer to avoid. Keyword list only — not nutritional advice.',
    category: 'food',
    terms: [
      { label: 'Monosodium Glutamate', aliases: ['MSG', 'sodium glutamate', 'E621', 'glutamat', 'monosodyum glutamat', 'glutamik asit', 'yeast extract'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Aspartame', aliases: ['E951', 'nutrasweet', 'equal', 'canderel', 'aspartam'], category: 'food', severity: 'notice', enabled: true },
      { label: 'High Fructose Corn Syrup', aliases: ['HFCS', 'isoglucose', 'fruktose corn syrup', 'fruktoz şurubu', 'yüksek fruktozlu mısır şurubu', 'glukoz fruktoz şurubu'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Sodium Nitrite', aliases: ['E250', 'nitrite', 'sodium nitrite', 'potassium nitrite', 'sodyum nitrit', 'potasyum nitrit'], category: 'food', severity: 'warning', enabled: true },
      { label: 'Sodium Nitrate', aliases: ['E251', 'nitrate', 'sodium nitrate', 'potassium nitrate', 'sodyum nitrat', 'potasyum nitrat'], category: 'food', severity: 'warning', enabled: true },
      { label: 'Tartrazine', aliases: ['E102', 'FD&C Yellow 5', 'yellow 5', 'tartrazin'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Sunset Yellow', aliases: ['E110', 'FD&C Yellow 6', 'yellow 6', 'sunset yellow FCF'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Allura Red', aliases: ['E129', 'FD&C Red 40', 'red 40', 'allura red AC'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Carmine', aliases: ['E120', 'cochineal', 'natural red 4', 'karmin'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Brilliant Blue', aliases: ['E133', 'FD&C Blue 1', 'blue 1', 'brilliant blue FCF'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Potassium Bromate', aliases: ['E924', 'potassium bromate', 'potasyum bromat'], category: 'food', severity: 'warning', enabled: true },
      { label: 'BHA', aliases: ['butylated hydroxyanisole', 'E320'], category: 'food', severity: 'notice', enabled: true },
      { label: 'BHT', aliases: ['butylated hydroxytoluene', 'E321'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Sodium Benzoate', aliases: ['E211', 'sodium benzoate', 'sodyum benzoat', 'benzoic acid', 'benzoik asit'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Azodicarbonamide', aliases: ['ADA', 'azodikarbonamid'], category: 'food', severity: 'warning', enabled: true },
      { label: 'Artificial Sweetener', aliases: ['sucralose', 'saccharin', 'acesulfame K', 'E950', 'E954', 'E955', 'E950', 'E951', 'E952', 'E954', 'E955', 'E957', 'E959', 'yapay tatlandırıcı', 'sükraloz', 'sakarin', 'asesülfam K'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Palm Oil', aliases: ['palm oil', 'palm kernel oil', 'palm stearin', 'palm olein', 'palmiste yağı', 'palm yağı', 'palmiye yağı'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Carrageenan', aliases: ['E407', 'carrageenan', 'karragen'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Soy Lecithin', aliases: ['E322', 'soya lesitini', 'soy lecithin'], category: 'food', severity: 'info', enabled: true },
      { label: 'Sorbic Acid', aliases: ['E200', 'sorbic acid', 'potassium sorbate', 'sorbik asit', 'potasyum sorbat'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Propionic Acid', aliases: ['E280', 'propionic acid', 'sodium propionate', 'calcium propionate', 'propiyonik asit', 'sodyum propiyonat', 'kalsiyum propiyonat'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Potassium Sorbate', aliases: ['E202', 'potassium sorbate', 'potasyum sorbat'], category: 'food', severity: 'info', enabled: true },
      { label: 'Titanium Dioxide', aliases: ['E171', 'titanium dioxide', 'titanyum dioksit', 'titanyum oksit'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Maltodextrin', aliases: ['maltodextrin', 'maltodekstrin'], category: 'food', severity: 'info', enabled: true },
      { label: 'Xanthan Gum', aliases: ['E415', 'xanthan gum', 'ksantan zamkı'], category: 'food', severity: 'info', enabled: true },
      { label: 'Guar Gum', aliases: ['E412', 'guar gum', 'guar zamkı'], category: 'food', severity: 'info', enabled: true },
      { label: 'Lactose', aliases: ['laktoz', 'süt şekeri'], category: 'food', severity: 'info', enabled: true },
      { label: 'Invert Sugar', aliases: ['invert sugar syrup', 'invert şeker', 'invert şeker şurubu'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Cellulose', aliases: ['E460', 'microcrystalline cellulose', 'methyl cellulose', 'selüloz', 'mikrokristalin selüloz', 'metil selüloz'], category: 'food', severity: 'info', enabled: true },
      { label: 'Vanillin', aliases: ['vanillin', 'ethyl vanillin', 'vanilya', 'vanilin', 'etil vanilin'], category: 'food', severity: 'info', enabled: true },
    ],
  },
  {
    id: 'palm-oil-derivatives',
    name: 'Palm Oil & Derivatives',
    description: 'Palm oil derivatives found in food, cosmetics, and cleaning products. Keyword list only — not a certified palm-free claim.',
    category: 'food',
    terms: [
      { label: 'Palm Oil', aliases: ['palm oil', 'palm kernel oil', 'palm olein', 'palm stearin', 'palm fruit oil', 'red palm oil', 'palmiste yağı', 'palm yağı', 'palmiye yağı', 'hurma yağı'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Palm Glyceride', aliases: ['palm glycerides', 'hydrogenated palm glyceride', 'palm gliserid', 'hidrojene palm gliserid'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Palmitate', aliases: ['retinyl palmitate', 'cetyl palmitate', 'ethylhexyl palmitate', 'isopropyl palmitate', 'sorbitan palmitate', 'ascorbyl palmitate', 'palmitat'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Cetyl Alcohol', aliases: ['cetyl alcohol', 'cetanol', 'cetylstearyl alcohol', 'setil alkol'], category: 'cosmetics', severity: 'info', enabled: true },
      { label: 'Stearyl Alcohol', aliases: ['stearyl alcohol', 'stearil alkol'], category: 'cosmetics', severity: 'info', enabled: true },
      { label: 'Cetearyl Alcohol', aliases: ['cetearyl alcohol', 'ceteareth', 'setearil alkol'], category: 'cosmetics', severity: 'info', enabled: true },
      { label: 'Glyceryl Stearate', aliases: ['glyceryl stearate', 'glyceryl monostearate', 'gliseril stearat'], category: 'cosmetics', severity: 'info', enabled: true },
      { label: 'Stearate', aliases: ['magnesium stearate', 'calcium stearate', 'zinc stearate', 'sodium stearate', 'stearic acid', 'stearat', 'magnezyum stearat', 'kalsiyum stearat', 'stearik asit'], category: 'food', severity: 'info', enabled: true },
      { label: 'Sorbitan', aliases: ['sorbitan monostearate', 'sorbitan tristearate', 'sorbitan oleate', 'sorbitan sesquioleate', 'sorbitan'], category: 'food', severity: 'info', enabled: true },
      { label: 'Palm Alcohol', aliases: ['palm alcohol', 'palmityl alcohol', 'palm alkol'], category: 'cosmetics', severity: 'info', enabled: true },
      { label: 'Sodium Laureth Sulfate', aliases: ['sodium laureth sulfate', 'SLES', 'sodium palm kernelate', 'sodyum lauret sülfat', 'sodyum palm çekirdeği'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Sodium Palmate', aliases: ['sodium palmate', 'sodium palm kernelate', 'sodium cocoate', 'sodyum palmat', 'sodyum palm çekirdeği'], category: 'cosmetics', severity: 'info', enabled: true },
      { label: 'Palm Acid', aliases: ['palm acid', 'palm asit'], category: 'cosmetics', severity: 'info', enabled: true },
    ],
  },
  {
    id: 'caffeine-stimulants',
    name: 'Caffeine & Stimulants',
    description: 'Common stimulants found in foods, drinks, and supplements. Keyword list only — not health advice.',
    category: 'food',
    terms: [
      { label: 'Caffeine', aliases: ['caffeine', 'coffee', 'caffein', 'kafein', 'kahve'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Guarana', aliases: ['guarana extract', 'guarana seed', 'guarana tohumu', 'guarana özü'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Taurine', aliases: ['taurine', 'tau', 'taurin'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Green Tea Extract', aliases: ['green tea', 'matcha', 'EGCG', 'yeşil çay', 'yeşil çay özü', 'matcha', 'kateşin'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Yerba Mate', aliases: ['yerba mate', 'mate tea', 'mate yaprağı', 'mate çayı'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Guarana Seed', aliases: ['guarana seed', 'guarana tohumu'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Theobromine', aliases: ['theobromine', 'cocoa', 'cacao', 'teobromin', 'kakao'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Black Tea Extract', aliases: ['black tea', 'siyah çay', 'siyah çay özü'], category: 'food', severity: 'info', enabled: true },
      { label: 'Kola Nut', aliases: ['kola nut', 'cola nut', 'kola cevizi'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Ginseng', aliases: ['ginseng', 'panax ginseng', 'ginseng root', 'ginseng kökü'], category: 'food', severity: 'info', enabled: true },
      { label: 'Energy Blend', aliases: ['energy blend', 'energy complex', 'enerji karışımı'], category: 'food', severity: 'info', enabled: true },
    ],
  },
];
