import type { PresetPack } from '../types/ingredients';

export const PRESET_PACKS: PresetPack[] = [
  {
    id: 'common-food-allergens',
    name: 'Common Food Allergens',
    description: 'Major food allergens recognized by labeling regulations. Keyword list only — not medical advice.',
    category: 'allergen',
    terms: [
      { label: 'Milk', aliases: ['lactose', 'casein', 'whey', 'milk protein', 'milk powder', 'süt', 'laktoz', 'süt tozu', 'süt proteini', 'kazein', 'peynir altı suyu'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Egg', aliases: ['eggs', 'albumin', 'lysozyme', 'ovomucin', 'egg white', 'egg yolk', 'egg powder', 'yumurta', 'yumurta akı', 'yumurta sarısı', 'yumurta tozu'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Fish', aliases: ['cod', 'salmon', 'anchovy', 'sardine', 'tuna', 'haddock', 'trout', 'balık', 'somon', 'ton', 'hamsi', 'sardalya'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Shellfish', aliases: ['shrimp', 'crab', 'lobster', 'prawn', 'crawfish', 'mussel', 'oyster', 'scallop', 'kabuklu deniz', 'karides', 'istakoz', 'yengeç'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Tree Nuts', aliases: ['almond', 'cashew', 'walnut', 'pecan', 'pistachio', 'hazelnut', 'macadamia', 'brazil nut', 'fındık', 'badem', 'ceviz', 'antep fıstığı', 'yer fıstığı'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Peanuts', aliases: ['peanut', 'arachis hypogaea', 'peanut butter', 'peanut oil', 'yer fıstığı', 'yer fıstığı yağı', 'fıstık ezmesi'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Wheat', aliases: ['wheat flour', 'wheat starch', 'wheat gluten', 'wheat protein', 'buğday', 'buğday unu', 'buğday nişastası'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Gluten', aliases: ['wheat gluten', 'barley', 'rye', 'oat gluten', 'triticale', 'glüten', 'arpa', 'çavdar'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Soy', aliases: ['soybean', 'soya', 'soy lecithin', 'soy protein', 'soy flour', 'soy oil', 'soja', 'soya lesitini', 'soya proteini', 'soya unu'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Sesame', aliases: ['sesame seeds', 'sesame oil', 'tahini', 'sesame paste', 'susam', 'susam yağı', 'tahin'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Celery', aliases: ['celery seed', 'celery salt', 'celery extract', 'kereviz', 'kereviz tohumu'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Mustard', aliases: ['mustard seed', 'mustard oil', 'mustard flour', 'hardal', 'hardal tohumu', 'hardal yağı'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Lupin', aliases: ['lupin bean', 'lupin flour', 'lupin protein', 'lupin tohumu'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Molluscs', aliases: ['snail', 'squid', 'cuttlefish', 'octopus', 'salyangoz', 'ahtapot', 'kalamar'], category: 'allergen', severity: 'warning', enabled: true },
      { label: 'Sulphites', aliases: ['sulfites', 'sulphur dioxide', 'sodium sulfite', 'E220', 'E221', 'E222', 'E223', 'sülfit', 'kükürt dioksit'], category: 'allergen', severity: 'warning', enabled: true },
    ],
  },
  {
    id: 'vegan-animal-derived',
    name: 'Vegan / Animal-Derived',
    description: 'Ingredients derived from animals. Keyword list only — not a vegan certification.',
    category: 'vegan',
    terms: [
      { label: 'Gelatin', aliases: ['gelatine', 'gel', 'jelatin', 'jelatin'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Collagen', aliases: ['hydrolyzed collagen', 'marine collagen', 'bovine collagen', 'kolajen', 'hidrolize kolajen'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Carmine', aliases: ['cochineal', 'carminic acid', 'CI 75470', 'E120', 'natural red 4'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Lanolin', aliases: ['wool wax', 'wool grease', 'lanolin alcohol', 'lanolin yağı'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Beeswax', aliases: ['cera alba', 'cire d\'abeille', 'balmumu', 'arı mumu'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Casein', aliases: ['sodium caseinate', 'calcium caseinate', 'kazein', 'sodyum kazeinat'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Whey', aliases: ['whey protein', 'whey powder', 'peynir altı suyu', 'whey proteini'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Shellac', aliases: ['confectioner\'s glaze', 'lac resin', 'E904'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Tallow', aliases: ['rendered fat', 'sodium tallowate', 'iç yağı', 'don yağı'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Honey', aliases: ['bal'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Keratin', aliases: ['hydrolyzed keratin', 'keratin protein', 'keratin'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Silk', aliases: ['silk amino acid', 'hydrolyzed silk', 'sericin', 'silk protein', 'ipek', 'ipek proteini'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Elastin', aliases: ['hydrolyzed elastin', 'elastin protein', 'elastin'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Cholesterol', aliases: ['cholesterol', 'kolesterol'], category: 'vegan', severity: 'warning', enabled: true },
      { label: 'Stearic Acid', aliases: ['stearate', 'magnesium stearate', 'stearik asit'], category: 'vegan', severity: 'notice', enabled: true },
    ],
  },
  {
    id: 'cosmetics-watchlist',
    name: 'Cosmetics Watchlist',
    description: 'Common cosmetic ingredients some users prefer to avoid. Keyword list only — not dermatology advice.',
    category: 'cosmetics',
    terms: [
      { label: 'Paraben', aliases: ['methylparaben', 'propylparaben', 'butylparaben', 'ethylparaben', 'isobutylparaben', 'benzylparaben', 'sodium methylparaben', 'parabenler'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Fragrance', aliases: ['parfum', 'perfume', 'aroma', 'fragrance oil', 'parfüm', 'aroma', 'koku', 'parfümlü'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Alcohol Denat', aliases: ['alcohol denatured', 'SD alcohol', 'denatured alcohol', 'denatüre alkol', 'etanol denat'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'SLS', aliases: ['sodium lauryl sulfate', 'sodium dodecyl sulfate', 'sodyum lauril sülfat'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'SLES', aliases: ['sodium laureth sulfate', 'sodium lauryl ether sulfate', 'sodyum lauret sülfat'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Phthalate', aliases: ['diethyl phthalate', 'DBP', 'DEHP', 'DEP', 'phthalates', 'ftalat', 'ftalatlar'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Formaldehyde', aliases: ['formalin', 'formaldehyde releaser', 'DMDM hydantoin', 'quaternium-15', 'imidazolidinyl urea', 'diazolidinyl urea', 'bronopol', 'formaldehit'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Triclosan', aliases: ['triclocarban', 'microban', 'triklosan'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'BHA', aliases: ['butylated hydroxyanisole', 'E320', 'BHA'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'BHT', aliases: ['butylated hydroxytoluene', 'E321', 'BHT'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Mineral Oil', aliases: ['paraffinum liquidum', 'petrolatum', 'mineral oil', 'paraffin', 'petrolatum', 'mineral yağ', 'parafin'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'Dimethicone', aliases: ['cyclomethicone', 'cyclotetrasiloxane', 'cyclopentasiloxane', 'silicone', 'dimetikon', 'silikon'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'Oxybenzone', aliases: ['benzophenone-3', 'BP-3', 'oxybenzone', 'oksibenzon'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Octinoxate', aliases: ['ethylhexyl methoxycinnamate', 'octyl methoxycinnamate', 'OMC', 'oktinoksat'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Coal Tar', aliases: ['coal tar dye', 'CI 77266', 'D&C Black', 'kömür katranı'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Hydroquinone', aliases: ['hydroquinone', 'hidrokinon'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Toluene', aliases: ['toluene', 'toluen'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Methylisothiazolinone', aliases: ['MI', 'MIT', 'methylchloroisothiazolinone', 'MCI', 'metilizotiyazolinon'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Propylene Glycol', aliases: ['propanediol', 'PG', 'propilen glikol'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'DEA', aliases: ['diethanolamine', 'MEA', 'monoethanolamine', 'TEA', 'triethanolamine', 'cocamide DEA', 'dietanolamin', 'trietanolamin'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Phenoxyethanol', aliases: ['phenoxyethanol', 'fenoksietanol'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'Synthetic Fluorphlogopite', aliases: ['synthetic fluorphlogopite', 'mica', 'sentetika mika'], category: 'cosmetics', severity: 'info', enabled: true },
      { label: 'PEG', aliases: ['polyethylene glycol', 'PEG-8', 'PEG-40', 'PEG-100', 'polietilen glikol'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'Retinyl Palmitate', aliases: ['retinyl palmitate', 'retinol palmitate', 'vitamin A palmitate'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'Talc', aliases: ['talcum powder', 'talc', 'talk'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'Sodium Benzoate', aliases: ['E211', 'sodium benzoate', 'sodyum benzoat'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'Potassium Sorbate', aliases: ['E202', 'potassium sorbate', 'potasyum sorbat'], category: 'cosmetics', severity: 'info', enabled: true },
      { label: 'Triclocarban', aliases: ['triclocarban', 'TCC', 'triklokarban'], category: 'cosmetics', severity: 'warning', enabled: true },
      { label: 'Homosalate', aliases: ['homosalate', 'homosalat'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'Octocrylene', aliases: ['octocrylene', 'oktokrilen'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'Nanoparticles', aliases: ['nano zinc oxide', 'nano titanium dioxide', 'nano partikül'], category: 'cosmetics', severity: 'notice', enabled: true },
      { label: 'Resorcinol', aliases: ['resorcinol', 'resorsinol'], category: 'cosmetics', severity: 'warning', enabled: true },
    ],
  },
  {
    id: 'sensitive-skin',
    name: 'Sensitive Skin Irritants',
    description: 'Common skin irritants that may cause reactions for sensitive skin types. Keyword list only — not dermatology advice.',
    category: 'sensitive_skin',
    terms: [
      { label: 'Fragrance', aliases: ['parfum', 'perfume', 'aroma', 'parfüm', 'koku'], category: 'sensitive_skin', severity: 'warning', enabled: true },
      { label: 'Alcohol Denat', aliases: ['alcohol denatured', 'SD alcohol', 'denatured alcohol', 'denatüre alkol'], category: 'sensitive_skin', severity: 'warning', enabled: true },
      { label: 'SLS', aliases: ['sodium lauryl sulfate', 'sodium dodecyl sulfate', 'sodyum lauril sülfat'], category: 'sensitive_skin', severity: 'warning', enabled: true },
      { label: 'SLES', aliases: ['sodium laureth sulfate', 'sodyum lauret sülfat'], category: 'sensitive_skin', severity: 'warning', enabled: true },
      { label: 'Methylisothiazolinone', aliases: ['MI', 'MIT', 'methylchloroisothiazolinone', 'MCI', 'metilizotiyazolinon'], category: 'sensitive_skin', severity: 'warning', enabled: true },
      { label: 'Propylene Glycol', aliases: ['propanediol', 'PG', 'propilen glikol'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'Lanolin', aliases: ['wool wax', 'lanolin alcohol', 'lanolin yağı'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'DEA', aliases: ['diethanolamine', 'triethanolamine', 'cocamide DEA', 'trietanolamin'], category: 'sensitive_skin', severity: 'warning', enabled: true },
      { label: 'Phenoxyethanol', aliases: ['phenoxyethanol', 'fenoksietanol'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'Retinol', aliases: ['retinol', 'retinoik asit', 'tretinoin', 'retinoid'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'Glycolic Acid', aliases: ['glycolic', 'AHA', 'alpha hydroxy acid', 'glikolik asit'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'Salicylic Acid', aliases: ['BHA', 'beta hydroxy acid', 'salisilik asit'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'Benzoyl Peroxide', aliases: ['benzoyl peroxide', 'benzoil peroksit'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'Essential Oil', aliases: ['essential oil blend', 'volatile oil', 'uçucu yağ', 'eterik yağ'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'Eucalyptus', aliases: ['eucalyptus oil', 'eucalyptol', 'okaliptüs'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'Peppermint', aliases: ['menthol', 'mentha piperita', 'nane yağı', 'mentol'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'Camphor', aliases: ['camphor', 'kapfor'], category: 'sensitive_skin', severity: 'notice', enabled: true },
      { label: 'Witch Hazel', aliases: ['hamamelis', 'witch hazel'], category: 'sensitive_skin', severity: 'info', enabled: true },
      { label: 'Citric Acid', aliases: ['citric acid', 'limon asidi', 'sitrik asit'], category: 'sensitive_skin', severity: 'info', enabled: true },
      { label: 'Sodium Hydroxide', aliases: ['lye', 'caustic soda', 'sodyum hidroksit'], category: 'sensitive_skin', severity: 'notice', enabled: true },
    ],
  },
  {
    id: 'cleaning-products',
    name: 'Cleaning Product Watchlist',
    description: 'Chemicals found in household cleaning products. Keyword list only — not safety advice.',
    category: 'cleaning',
    terms: [
      { label: 'Chlorine', aliases: ['sodium hypochlorite', 'chlorine bleach', 'klor', 'hipoklorit'], category: 'cleaning', severity: 'warning', enabled: true },
      { label: 'Ammonia', aliases: ['ammonium hydroxide', 'ammonia solution', 'amonyak', 'amonyum hidroksit'], category: 'cleaning', severity: 'warning', enabled: true },
      { label: 'Bleach', aliases: ['sodium hypochlorite', 'chlorine bleach', 'çamaşır suyu', 'ağartıcı'], category: 'cleaning', severity: 'warning', enabled: true },
      { label: 'Fragrance', aliases: ['parfum', 'perfume', 'aroma', 'scent', 'parfüm', 'koku'], category: 'cleaning', severity: 'notice', enabled: true },
      { label: 'Quats', aliases: ['quaternary ammonium compounds', 'benzalkonium chloride', 'ADBAC', 'cetrimonium bromide', 'kuarterner amonyum', 'benzalkonyum klorür'], category: 'cleaning', severity: 'warning', enabled: true },
      { label: 'Phosphates', aliases: ['sodium tripolyphosphate', 'STPP', 'trisodium phosphate', 'fosfat', 'sodyum trifosfat'], category: 'cleaning', severity: 'notice', enabled: true },
      { label: 'Optical Brighteners', aliases: ['fluorescent brightening agents', 'FBA', 'tinopal', 'CBS-X', 'optik beyazlatıcı'], category: 'cleaning', severity: 'notice', enabled: true },
      { label: 'Triclosan', aliases: ['triclocarban', 'microban', 'triklosan'], category: 'cleaning', severity: 'warning', enabled: true },
      { label: 'Nonylphenol', aliases: ['nonylphenol ethoxylate', 'NPE', 'nonilfenol'], category: 'cleaning', severity: 'warning', enabled: true },
      { label: 'MEA', aliases: ['monoethanolamine', 'MEA', 'etanolamin'], category: 'cleaning', severity: 'notice', enabled: true },
      { label: '2-Butoxyethanol', aliases: ['ethylene glycol monobutyl ether', 'EGBE', 'bütoksietanol'], category: 'cleaning', severity: 'warning', enabled: true },
      { label: 'EDTA', aliases: ['ethylenediaminetetraacetic acid', 'tetrasodium EDTA', 'disodium EDTA'], category: 'cleaning', severity: 'notice', enabled: true },
    ],
  },
  {
    id: 'food-additives',
    name: 'Food Additives to Watch',
    description: 'Common food additives some users prefer to avoid. Keyword list only — not nutritional advice.',
    category: 'food',
    terms: [
      { label: 'Monosodium Glutamate', aliases: ['MSG', 'sodium glutamate', 'E621', 'glutamat', 'monosodyum glutamat'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Aspartame', aliases: ['E951', 'nutrasweet', 'equal', 'aspartam'], category: 'food', severity: 'notice', enabled: true },
      { label: 'High Fructose Corn Syrup', aliases: ['HFCS', 'isoglucose', 'fruktoz şurubu', 'yüksek fruktozlu mısır şurubu'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Sodium Nitrite', aliases: ['E250', 'nitrite', 'sodyum nitrit'], category: 'food', severity: 'warning', enabled: true },
      { label: 'Sodium Nitrate', aliases: ['E251', 'nitrate', 'sodyum nitrat'], category: 'food', severity: 'warning', enabled: true },
      { label: 'Tartrazine', aliases: ['E102', 'FD&C Yellow 5', 'yellow 5', 'tartrazin'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Sunset Yellow', aliases: ['E110', 'FD&C Yellow 6', 'yellow 6'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Allura Red', aliases: ['E129', 'FD&C Red 40', 'red 40'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Carmine', aliases: ['E120', 'cochineal', 'natural red 4'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Brilliant Blue', aliases: ['E133', 'FD&C Blue 1', 'blue 1'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Potassium Bromate', aliases: ['E924', 'potassium bromate', 'potasyum bromat'], category: 'food', severity: 'warning', enabled: true },
      { label: 'BHA', aliases: ['butylated hydroxyanisole', 'E320'], category: 'food', severity: 'notice', enabled: true },
      { label: 'BHT', aliases: ['butylated hydroxytoluene', 'E321'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Sodium Benzoate', aliases: ['E211', 'sodyum benzoat'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Azodicarbonamide', aliases: ['ADA', 'azodikarbonamid'], category: 'food', severity: 'warning', enabled: true },
      { label: 'Artificial Sweetener', aliases: ['sucralose', 'saccharin', 'acesulfame K', 'E950', 'E954', 'E955', 'yapay tatlandırıcı', 'sükraloz', 'sakarin'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Palm Oil', aliases: ['palm oil', 'palm kernel oil', 'palm stearin', 'palmiste yağı', 'palm yağı'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Carrageenan', aliases: ['E407', 'carrageenan', 'karragen'], category: 'food', severity: 'notice', enabled: true },
      { label: 'Soy Lecithin', aliases: ['E322', 'soya lesitini'], category: 'food', severity: 'info', enabled: true },
    ],
  },
];
